import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from './components/Navbar';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Exposes the font as a CSS variable
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className={`${inter.variable}`}
    >
      <body className='min-h-full flex flex-col'>
        <Navbar />
        <main className='flex-1'>{children}</main>
      </body>
    </html>
  );
}
